### ISSUE TITLE
TypeError in essentia

### ISSUE THREAD

**Issue by beantowel** [juanjobosch/SourceFilterContoursMelody#3]
running

`$ python2 src/MelodyExtractionFromSingleWav.py <path to .wav> <path to output> --extractionMethod='BG2' --hopsize=0.01 --nb-iterations=2`

i got this error:
```
[   INFO   ] MusicExtractorSVM: no classifier models were configured by default
matplotlib or seaborn not available
iteration  0  over  2
iteration  1  over  2
Done!
Extracting melody from salience function
Traceback (most recent call last):
  File "src/MelodyExtractionFromSingleWav.py", line 131, in <module>
    main(sys.argv[1:])
  File "src/MelodyExtractionFromSingleWav.py", line 123, in main
    process(args)
  File "src/MelodyExtractionFromSingleWav.py", line 114, in process
    times, pitch = melodyExtractionFromSalienceFunction.MEFromSF(times, combSal, options)
  File "src/melodyExtractionFromSalienceFunction.py", line 154, in MEFromSF
    pool['allframes_SALsalience_peaks_saliences'])
  File "~/.local/lib/python2.7/site-packages/essentia/standard.py", line 118, in __call__
    return self.compute(*args)
  File "~/.local/lib/python2.7/site-packages/essentia/standard.py", line 95, in compute
    %(str(_c.determineEdt(arg)), str(goalType)))
TypeError: Error cannot convert argument LIST_ARRAY to VECTOR_VECTOR_REAL
```

**Comment by juanjobosch** [comment]
Thanks for reporting this error. It seems that essentia changed the way to handle arrays. 
I have adapted the code to make it work.
